swagger: '2.0'
info:
  version: 1.0.0
  title: Precon-Client
  description: Client API for precon.io
paths: 
  /user:
    post:
      summary: Add new user. 
      description: This endpoint is used for adding users.
      parameters:
        - name: user 
          in: body
          description: User Object
          required: true
          schema:
            $ref: '#/definitions/User'
      tags:
        - User      
      responses:
        201:
          description: User successfully added.
        400:
          description: Invalid email address.  
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  /interest:
    post:
      summary: Capture user interests. 
      description: The endpoint is used for capturing user interests.
      parameters:
        - name: interests
          in: body
          description: User interest Object.
          required: true
          schema:
            $ref: '#/definitions/Interest'
      tags:
        - User      
      responses:
        201:
          description: User interests successfully added.
        400:
          description: Invalid email address.  
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
            
  /search:
    get:
      summary: Search for contents. 
      description: The endpoint is used by user to search for contents. 
      parameters:
        - name: search
          in: query
          description: Search query string.
          required: true
          type: string
          format: string
      tags:
        - User      
      responses:
        200:
          description: Yayy..!! found some movies for you.
          schema:
            type: array
            items:
              $ref: '#/definitions/QueryResults'
        404:
          description: Ohh..!! could not find any related movies.
          schema:
            type: array
            items: 
              type: object
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'          
            
  /suggest:
    get:
      summary: Gives content suggestions for user. 
      description: The endpoint is used for recommending related contents for user.
      parameters:
      - name: user
        in: query
        description: User email address.
        required: true
        type: string
        format: email
      tags:
        - User      
      responses:
        200:
          description: Cool..!! found some recommendations for you.
          schema:
            type: array
            items:
              $ref: '#/definitions/QueryResults'
        404:
          description: Ohh..!! could not find any related movies.
          schema:
            type: array
            items: 
              type: object
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    
definitions:
  User:
    type: object
    required:
      - email
    properties:
      email:
        description: Email id of the user.
        type: string
        format: email
      
      phone:
        description: Phone number of the user.
        type: integer
        format: int32
        
      gender:
        description: Gender of the user.
        type: string
        format: string
      
      age:
        description: Age of the user.
        type: integer
        format: int32  
      
      country:
        description: Country of the user.
        type: string
        format: string
      
      sourceId:
        description: Source id given by the integrator
        type: string
        format: string
  
  Interest:
    type: object
    required:
      - email
      - contentSourceId
      - type
    properties:
      email:
        description: Email id of the user.
        type: string
        format: email
      
      contentSourceId:
        description: Source id of the content.
        type: string
        format: string   
      
      type: 
        description: Interest type.
        type: string
        enum: ['bookmarked', 'viewed', 'consumed']
        
      consumptionTime:
        description: If interest type is 'consumed' then consumptionTime is the total time consumed by the user for a particular content, else it is optional in remaining cases.
        type: integer
        format: int32
  
  QueryResults:
    type: object
    properties:
      sourceId:
        description: Unique id of the content as per the integration system.
        type: string
        format: string  
        
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string