swagger: '2.0'
info:
  version: 1.0.0
  title: Precon-Client
  description: Client API for precon.io
paths: 
  /user:
    post:
      summary: Add new user. 
      description: The endpoint is used for adding users.
      parameters:
        - name: user 
          in: body
          description: User Object
          required: true
          schema:
            $ref: '#/definitions/User'
      tags:
        - User      
      responses:
        200:
          description: User successfully added.
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  /interest:
    post:
      summary: Capture user interests. 
      description: The endpoint is used for capturing user interests.
      parameters:
        - name: interests
          in: body
          description: User interest Object.
          required: true
          schema:
            $ref: '#/definitions/Interest'
      tags:
        - User      
      responses:
        200:
          description: User interests successfully added.
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
            
  /search:
    get:
      summary: Search for contents. 
      description: The endpoint is used by user to search for contents. 
      parameters:
        - name: search
          in: query
          description: Search query string.
          required: true
          type: string
          format: string
      tags:
        - User      
      responses:
        200:
          description: Yayy..!! found some movies for you.
          schema:
            type: array
            items:
              $ref: '#/definitions/SearchResults'
        404:
          description: Ohh..!! could not find any related movies.
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'          
            
  /suggest:
    get:
      summary: Returns suggestions for user. 
      description: The endpoint is used for recommending related contents for user.
      parameters:
      - name: user
        in: body
        description: User Object
        required: true
        schema:
          $ref: '#/definitions/User'
      tags:
        - User      
      responses:
        200:
          description: Cool..!! found some recommendations for you.
          schema:
            type: array
            items:
              $ref: '#/definitions/SearchResults'
        404:
          description: Ohh..!! could not find any related movies.
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    
definitions:
  User:
    type: object
    required:
      - email
    properties:
      email:
        description: email id of the user.
        type: string
        format: email
      
      phone:
        description: phone number of the user.
        type: integer
        format: int32
        
      gender:
        description: gender of the user.
        type: string
        format: string
      
      age:
        description: age of the user.
        type: integer
        format: int32  
      
      country:
        description: country of the user.
        type: string
        format: string
      
      sourceId:
        description: source id from the integrator
        type: string
        format: string
  
  Interest:
    type: object
    required:
      - email
      - contentSourceId
    properties:
      email:
        description: email id of the user.
        type: string
        format: email
      
      contentSourceId:
        description: source id of the content.
        type: string
        format: string    
  
  SearchResults:
    type: object
    properties:
      title:
        description: Title of the content.
        type: string
        format: string
      type:
        description: Type of the content - movie, video, tvshow, tvseries.
        type: string
        format: string
      classification:
        description: Comma seperated list of tags or genere or classification of the content. Like music, video, rap, punjabi Or sports, cricket, highlights or biopic, sports 
        type: string
        format: string
      sourceId:
        description: Unique id of the content as per the integration system.
        type: string
        format: string  
      integrationId:
        description: Unique id of the integrator as per the integration system.
        type: string
        format: string
      language:
        description: Language of the content.
        type: string
        format: string
      runningTimeInSecs:
        description: Playback time of the content in seconds.
        type: integer
        format: int32
      cast:
        description: Comma separated list of cast starring in the content.
        type: string
        format: string
      directors:
        description: Comma separated list of directors.
        type: string
        format: string
      studios:
        description: Comma separated list of studios.
        type: string
        format: string
      releasedOn:
        description: Date on which the content was released.
        type: string
        format: date
      synopsis:
        description: Synopsis of the content.
        type: string
        format: string
      keywords:
        description: keywords related to content.
        type: string
        format: string
        
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string